# Generated by Django 5.1.4 on 2025-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comments_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.IntegerField(null=True),
        ),
    ]
