# Generated by Django 5.1.4 on 2025-03-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comments_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
